version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - 80:80
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - ./src:/var/www/html
      - ./docker/apache/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - net1

  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - net1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    networks:
      - net1

networks:
  net1:
